### GET request to get devices by state

#valid state
GET http://localhost:4000/api/v1/devices?state=IN_USE


### GET request to get devices by state

#invalid state
GET http://localhost:4000/api/v1/devices?state=in

