### GET request to get device by ID
GET http://localhost:8080/api/v1/devices/333e4567-e89b-12d3-a456-426614174014

### GET request to get device by invalid ID
GET http://localhost:8080/api/v1/devices/333

### GET request to get device by ID that does not exist
GET http://localhost:8080/api/v1/devices/333e4567-e89b-12d3-a456-42661417401