### GET request to get all devices
GET http://localhost:4000/api/v1/devices?page=1&size=10

### GET request to get all devices sorted by brand ascending
GET http://localhost:4000/api/v1/devices?sort=brand,asc

### GET request to get all devices sorted by brand ascending and state descending
GET http://localhost:4000/api/v1/devices?sort=brand,asc&sort=state,desc

###